version: "3.9"  # optional since v1.27.0
services:
  bidder:
    image: harshit54/greedygame-bidder
    ports:
      - "3001:3001"

  auctioneer:
    image: harshit54/greedygame-auctioneer
    ports:
      - "3000:3000"      

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1